FROM python:3

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src/stats.py .
COPY src/utils utils
COPY .env .

CMD [ "python3", "-u", "./stats.py" ]