version: "3.9"
services:
  web:
    build: ./flash-server
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
  auto-velo:
    build: ./sheldule-server
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
