version: "3.9"
services:
  auto-velo:
    build:
        context: .
        dockerfile: Dockerfile-server
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart:
      unless-stopped

  stats-velo:
    build:
        context: .
        dockerfile: Dockerfile-stats
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "velo-data:/data"
    restart:
      unless-stopped

volumes:
  velo-data:
